[versions]
agp = "8.8.0"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
coreKtx = "1.15.0"
androidx-activity-compose = "1.9.3"
# 使用 AndroidX Compose BOM 来管理版本 (稳定版)
composeBom = "2024.10.01"
kotlinxSerializationJson = "1.7.3"
xposedApi = "82"
yukihookApi = "1.3.1"
yukonga-miuix = "0.7.2"
haze = "1.1.1"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
lsplugin-apksign = { id = "org.lsposed.lsplugin.apksign", version = "1.4" }
lsplugin-resopt = { id = "org.lsposed.lsplugin.resopt", version = "1.6" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# 必须加上 version.ref = "kotlin"，因为它是 Kotlin 编译器的一部分
parcelize = { id = "kotlin-parcelize", version.ref = "kotlin" }
# 使用官方 Compose 编译器插件
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
xposedApi = { group = "de.robv.android.xposed", name = "api", version.ref = "xposedApi" }
yukihookApi = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukihookApi" }
yukihookKsp = { group = "com.highcapable.yukihookapi", name = "ksp-xposed", version.ref = "yukihookApi" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
yukonga-miuix = { group = "top.yukonga.miuix.kmp", name = "miuix", version.ref = "yukonga-miuix" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }

# ⬇️ 标准 AndroidX Compose 库 (BOM)
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
# ✅ 新增：布局库 (解决 Box, align 等报错)
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
# ✅ 新增：扩展图标库 (解决 Search, Settings, Info 图标报错)
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
